# Generated by Django 5.1.5 on 2025-02-02 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id_estudante', models.AutoField(primary_key=True, serialize=False)),
                ('nome_estudante', models.CharField(max_length=45)),
                ('matricula', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('bolsista_pae', models.BooleanField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('curso', models.CharField(choices=[('Computação', 'Computação'), ('Elétrica', 'Elétrica'), ('Superior - Computação', 'Superior - Computação'), ('Superior - Matemática', 'Superior - Matemática')], max_length=50)),
                ('deseja_caderno', models.BooleanField(default=False)),
                ('deseja_garrafa', models.BooleanField(default=False)),
                ('camisa', models.CharField(blank=True, choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('nome_material', models.CharField(max_length=45)),
                ('estoque_disponivel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id_requisicao', models.AutoField(primary_key=True, serialize=False)),
                ('data_requisicao', models.DateTimeField(auto_now_add=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisitions.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRequisicao',
            fields=[
                ('id_item_requisicao', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade_requisitada', models.IntegerField()),
                ('status', models.CharField(max_length=11)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisitions.material')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisitions.requisicao')),
            ],
        ),
    ]
