# Generated by Django 5.1.5 on 2025-02-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudante',
            name='data',
        ),
        migrations.AddField(
            model_name='estudante',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='estudante',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
